using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cinemachine;
using UnityEditor;
using UnityEngine.SceneManagement;

public class CameraControlTrigger : MonoBehaviour
{
    public CustomInspectorObjects   customInspectorObjects;
    
    private Collider2D _coll;

    private void Start()
    {
    }
    private void OnTriggerEnter2D(Collider2D collision)
    {   
        if (!CameraManager.Instance || !CameraManager.Instance.gameObject.activeInHierarchy) return;
        if (collision.GetComponentInParent<Ball>())
        {   
            if (customInspectorObjects.panCameraOnContact)
            {
                // pan the camera
				CameraManager.Instance.PanCameraOnContact(customInspectorObjects.panDistance,customInspectorObjects.panTime,customInspectorObjects.panDirection,false);
            }
        }
    }

    private void OnTriggerExit2D(Collider2D collision)
    {
        if (!CameraManager.Instance || !CameraManager.Instance.gameObject.activeInHierarchy) return;
        if (collision.GetComponentInParent<Ball>())
        {   
            if (customInspectorObjects.panCameraOnContact)
            {
                // pan the camera
                CameraManager.Instance.PanCameraOnContact(customInspectorObjects.panDistance,customInspectorObjects.panTime,customInspectorObjects.panDirection,true);
            }
        }
    }
}

//非 MonoBehaviour 类，它不能直接在 Inspector 中显示，除非它被标记为 可序列化。
//还需要在主类（继承monobehavior）public声明实例
[System.Serializable]
public class CustomInspectorObjects
{
    public bool swapCameras = false;
    public bool panCameraOnContact = false;

    [HideInInspector] public CinemachineVirtualCamera cameraOnLeft;
    [HideInInspector] public CinemachineVirtualCamera cameraOnRight; 

    [HideInInspector] public PanDirection panDirection;
    [HideInInspector] public float panDistance = 3.0f;
    [HideInInspector] public float panTime = 0.7f;
}
public enum PanDirection
{
    Up,
    Down,
    Left,
    Right
}
[CustomEditor(typeof(CameraControlTrigger))]
public class MyScriptEditor : Editor
{
    CameraControlTrigger cameraControlTrigger;

    private void OnEnable()
    {
        cameraControlTrigger = (CameraControlTrigger)target;
    }

    public override void OnInspectorGUI()
    {
        DrawDefaultInspector();

        if (cameraControlTrigger.customInspectorObjects.swapCameras)
        {
            cameraControlTrigger.customInspectorObjects.cameraOnLeft = EditorGUILayout.ObjectField("Camera on Left", cameraControlTrigger.customInspectorObjects.cameraOnLeft, typeof(CinemachineVirtualCamera), true) as CinemachineVirtualCamera;

            cameraControlTrigger.customInspectorObjects.cameraOnRight = EditorGUILayout.ObjectField("Camera on Right", cameraControlTrigger.customInspectorObjects.cameraOnRight, typeof(CinemachineVirtualCamera), true) as CinemachineVirtualCamera;
        }
        if (cameraControlTrigger.customInspectorObjects.panCameraOnContact)
        {
            cameraControlTrigger.customInspectorObjects.panDirection = (PanDirection)EditorGUILayout.EnumPopup("Camera Pan Direction", cameraControlTrigger.customInspectorObjects.panDirection);
            cameraControlTrigger.customInspectorObjects.panDistance = EditorGUILayout.FloatField("Pan Distance", cameraControlTrigger.customInspectorObjects.panDistance);
            cameraControlTrigger.customInspectorObjects.panTime = EditorGUILayout.FloatField("Pan Time", cameraControlTrigger.customInspectorObjects.panTime);
        }

        if (GUI.changed)
        {
            EditorUtility.SetDirty(cameraControlTrigger);
        }
    }
}
